<template>
<div> 
    <div id="header-wrap"></div>
    <div id="text"> <h3>Environment</h3> <p>CTDI has made a commitment to our employees, our community and our customers that we will continue to train and educate ourselves in waste minimization, hazardous material handling and regulatory compliance in an effort to support the longevity of the environment. CTDI is committed to protecting and preserving our natural resources in a productive and efficient manner through corporate initiatives such as recycling and resource management. CTDI has not incurred any regulatory fines or penalties as a result of improper environmental practices.</p> </div>
    <div id="white-space"></div>
        <div class="title"><h4>Energy Use and Our Carbon Footprint</h4></div>
    <div id="barchart_material"></div>
    <div id="mobile-chart-1"><img src="../assets/CTDI-Environment/mobile-chart-1.jpg" alt=" vertical bar chart"></div>
    <div class="graph-text container"><p>Since a majority of CTDI's carbon emissions comes from our use of electricity; reducing electric usage is one of our primary goals. In 2016, we implemented several building related improvements that reduced our energy footprint across multiple facilities. One improvement was through the transition to cloud-based data storage, which allowed CTDI to decommission 3 data servers from its headquarters, saving over 17,000 kWh in energy costs for the servers themselves, as well as reducing the building's cooling needs.</p>
      <br>
       <p>In another main CTDI building in South Bend, IN, a lighting retrofit was conducted that replaced HID lights with LED. This will save an estimated 50% in energy usage along with a reduction of heat generated by our current fixtures, which will save close to 600 tons CO2e in one building alone. To continue to ensure energy improvements, CTDI has set a carbon target for itself, to reduce the intensity of our GHG emissions per square foot of building space by 2% over a five year period from our 2014 baseline, or a 10% reduction overall. As of 2016, CTDI has reached its target.</p>
      </div>
    <div id="chart_div"></div>
    <div id="mobile-chart-2"><img src="../assets/CTDI-Environment/mobile-chart-2.png" alt="horizontal bar chart"></div>
     <br>
     <br>
    <div id="btn-group">
      <button class="btn btn-outline-dark" id="none">No Format</button>
      <button class="btn btn-outline-dark" id="scientific">Scientific Notation</button>
      <button class="btn btn-outline-dark" id="decimal">Decimal</button>
      <button class="btn btn-outline-dark" id="short">Short</button>
    </div>
    <br><p class="container graph-end">Because the square footage increased more than originally predicted, CTDI is considering other performance standards.</p>
    <div id="header-wrap-2"></div>
    <div id="text-2"> <h3>Waste and Resource Conservation</h3> 
    <br><p>CTDI sends all waste from our seven Southeastern PA facilities to Blue River Resource in Wilmington, Delaware. The cutting edge Blue River facility ensures that any waste or recyclable material CTDI generates at the headquarter location, is responsibly processed and recycled. Blue River recycles 98% of all materials that comes in. The remaining 2% of materials are burned to generate electricity.</p>
    <br><p>CTDI is working to minimize printing in our daily operations, which leads to paper, ink and toner savings. We have enlisted an outside company to install network software to document our printing. We also recycle cooking by-products, such as oil in some of our locations.</p>
    <br><p>CTDI engages with our customers to reduce waste as well. CTDI has partnered with Verizon in a large electronics recycling initiative at CTDI's Headquarters in West Chester. CTDI and Verizon collected over 67,350 pounds of electronics from more than 500 CTDI and community participants, resulting in Verizon to achieve their "1 Million Pounds Recycled" milestone at the event. As a result of the event, 67,350 pounds of electronics were collected that equated to the avoidance of 105 metric tons (MT) of CO2. In addition, Verizon calculated that the FiOS STB Clean & Screen Program managed by CTDI, which allows Verizon to reuse STBs vs. new manufacturing, avoided 313K pounds of new material generation.  This collection of STBs equated to the avoidance of 454MT of CO2.</p>
    <br><p>CTDI is currently pursuing zero waste-to-landfill certifications at five of its facilities. Our Phoenix, AZ facility achieved this goal in June of 2017.</p>
    <br>
     <!-- overlay link -->
        <div class="content-1">
    <router-link to=/sustainability/environment/zero>
      <div class="content-overlay-1"></div>
      <img class="content-image-1" src="../assets/CTDI-Environment/waterfall-stairs.jpg" alt="waterfall with stairs"> 
      <div class="content-details-1 fadeIn-top">
        <h5>Project Page</h5>
        <p>Click here for more information</p>
      </div>
      <h6>Zero Waste</h6>
    </router-link>
  </div>
    </div>
    <div id="white-space-2"></div>
    <div class="title"><h4>Our Products and Services</h4></div>
     <div class="text-p container"><p>The very nature of CTDI’s business has sustainability at the core. We test and repair millions of pieces of customer equipment each year, allowing our customers to reuse and repurpose equipment rather than discarding and buying new. CTDI's model of repairing equipment as opposed to discarding and replacing it is inherently better for the earth and our customers' budgets. From an energy perspective, a refurbished component is estimated to require 32% of the energy of a newly manufactured set top box. CTDI saves an estimated 244,800 megawatt hours of energy each year based on its refurbishment of 250,000 set top boxes each month. In addition to repairing and refurbishing equipment, we re-use packaging and electronic parts wherever possible.</p></div>
     <div id="header-wrap-3"></div>
    <div id="text-3"> <h3>Product Packaging</h3> 
    <p>CTDI's Operations teams work closely with our packaging suppliers to design cartons which safely transport our customers' products in the most environmentally friendly manner. The following are some of the initiatives we have in place.</p>
      <div class="pack-flex">
        <li class="pack-item fa fa-caret-right">Efficient Packaging Solution: Dimensional data capture of all products and outbound shipping cartons allows for the systematic determination of the optimal shipping carton, resulting in reduced waste and maximization of trailer space.</li>
        <li class="pack-item fa fa-caret-right">Reusable Packaging: CTDI packaging is reused until the physical characteristics fall below our Quality Assurance acceptable limits. This approach promotes improving total cost of ownership and reduces the environmental impact of the container. In some instances, the cartons are shipped back to the manufacturer for disassembly and reuse in new package construction. Those cartons that cannot be reused in construction are recycled.</li>
        <li class="pack-item fa fa-caret-right">Reusable Foam Inserts: Wherever possible, CTDI reuses the foam inserts used to protect units during the shipping process if they meet our quality standards.</li>
        <li class="pack-item fa fa-caret-right">Relabeling Packaging: In some operations, boxes that are shipped to CTDI with a return are relabeled for reuse if they are in a condition that meets our quality standards. These labels return the carton to "like-new" condition.</li>
        <li class="pack-item fa fa-caret-right">Post-Consumer Material: CTDI's packaging suppliers are required to utilize post-consumer recycled material.</li>
        <li class="pack-item fa fa-caret-right">Certified Material: CTDI clearly communicates our commitment regarding the use of renewable resources to our key suppliers. In our packaging requirements, we request the use of material certified by the Sustainable Forestry Initiative (SFI). The SFI forest certification and chain-of-custody certification promotes responsible forestry practices which tracks fiber content from forest through to production of packaging. Measures of SFI certified material and recycled content can be verified for companies to claim in their CSR reports as well as customer compliance reports.</li>
        <li class="pack-item fa fa-caret-right">Package Design: CTDI has diligently worked with its packaging suppliers to reduce waste by re-designing any non-recyclable packaging materials, such as foam, to a recyclable design without compromising quality or cosmetics. CTDI's Operations teams works closely with our packaging suppliers to design cartons which safely transports our customers' products in the most environmentally friendly manner.</li>
      </div>
    </div>
    <div class="title"><h4>Management Systems Certifications</h4>
    <p>Ten of CTDI's facilities are ISO 14001 certified, in addition one more CTDI facility will pursue ISO 14001 certification in 2017. CTDI has also achieved OHSAS 18001 certification of its Occupational Health and Safety Management System in Buford, GA in 2015, and in Bessemer, AL in 2016.</p>
      <!-- overlay link -->
        <div class="content-1">
    <router-link to=/sustainability/environment/zero>
      <div class="content-overlay-1"></div>
      <img class="content-image-1" src="../assets/CTDI-Environment/safety.jpg" alt="waterfall with stairs"> 
      <div class="content-details-1 fadeIn-top">
        <h5>OHSAS 18001 Certification</h5>
        <p>Click here for more information</p>
      </div>
      <h6>Management Systems</h6>
    </router-link>
  </div>
    </div>
      <div class="title"><h4>Environmental Impact Data</h4>
      </div>
      <div id="table_div"></div>
      <div id="table_div_2"></div>
      <div id="white-space-2"></div>
      <div id="white-space-2"></div>
      
<div class="container">
<div class="divider"></div>
</div>
       <!-- hover overlay -->
 <div class="overlay-container">
    <div class="content">
    <router-link to=/sustainability/community>
      <div class="content-overlay"></div>
        <img class="content-image" src="../assets/CTDI-Sustainability/community.jpg" alt="community of people">     
        <div class="content-details fadeIn-top">
        <h3>Community</h3>
        <p>For over 40 years, CTDI has promoted a corporate culture of community leadership.</p>
      </div>
      <h6>Community</h6>
    </router-link>
  </div>
  <div class="content">
    <router-link to=/sustainability/ethics>
      <div class="content-overlay"></div>
      <img class="content-image" src="../assets/CTDI-Sustainability/ethics-1.jpg" alt="cabinet full of books"> 
      <div class="content-details fadeIn-right">
        <h3>Ethics</h3>
        <p>CTDI and its subsidiaries conduct business consistent with our long established corporate values.</p>
      </div>
       <h6>Ethics</h6>
    </router-link>
  </div>
</div>
  

     <div id="to-top"><a class="fa fa-arrow-circle-o-up"  v-on:click="toTop">Back to top</a></div>  
</div>
</template>



<script>

  export default {
    name: 'Environment',
    data() {
      return {
       
    }
  },
    created() {
    
  },

   methods: {  
      drawChart: function() {
          var data = google.visualization.arrayToDataTable([
          ['tonnes CO²e', '2014', '2015', '2016'],
          ['Scope 1 (direct emissions)', 5946, 8798, 8157],
          ['Scope 2 (purchased electricity)', 34513, 32369, 36508]
        ]);

        var options = {
          chart: {
            title: 'Greenhouse Gas Emissions',
            subtitle: 'In 2016, CTDI utilized 85,833 MWh of energy and emitted 45,588 metric tons of CO²e.',
            // width: 900
          },
          bars: 'vertical' 
        };

        var chart = new google.charts.Bar(document.getElementById('barchart_material'));

        chart.draw(data, google.charts.Bar.convertOptions(options));
      },
      drawChart2: function() {
               var data = google.visualization.arrayToDataTable([
          ['Year', 'Projected S1&2 emissions', 'Actual S1&2 emissions'],
          ['2014', 40485, 40485 ],
          ['2015', 41659, 41167 ],
          ['2016', 42867, 44665 ],
          ['2017', 44110, 0  ],
          ['2018', 45390, 0 ],
          ['2019', 46706, 0 ]
        ]);

        var options = {
          chart: {
            title: 'Direct Greenhouse Gas Emissions (in metric tons CO²e)',
            subtitle: 'projected intensity assumes 5% growth each year in square footage',
          },
          bars: 'horizontal', 
          hAxis: {format: 'decimal'},
          
          colors: ['#1b9e77', '#d95f02', '#7570b3']
        };

        var chart = new google.charts.Bar(document.getElementById('chart_div'));

        chart.draw(data, google.charts.Bar.convertOptions(options));

        var btns = document.getElementById('btn-group');

        btns.onclick = function (e) {

          if (e.target.tagName == 'BUTTON') {
            options.hAxis.format = e.target.id === 'none' ? '' : e.target.id;
            chart.draw(data, google.charts.Bar.convertOptions(options));
                 } 
        }
      },
         drawChart3: function() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', '');
        data.addColumn('number', '2016 GHG Emissions (MT CO²e)');
        data.addRows([
          ['Scope 1',  {v: 8157, f: '8,157'}],
          ['Scope 2',  {v: 36508, f: '36,508'}],
          ['Scope 3 (Business Travel',  {v: 798, f: '798'}],
          ['Scope 3 (Tracked Waste)',  {v: 125, f: '125'}],
          ['Total',  {v: 45588, f: '45,588'}],
        ]);

        var table = new google.visualization.Table(document.getElementById('table_div'));

        table.draw(data, {showRowNumber: false, width: '100%', height: '100%'});
      },

        drawChart4: function() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', '');
        data.addColumn('number', 'Energy Type (MWh)');
        data.addRows([
          ['Distillate Fuel Oil #2',  {v: 20595, f: '20,595'}],
          ['Natural Gas',  {v: 13294, f: '13,294'}],
          ['Fuel Total',  {v: 33889, f: '33,889'}],
          ['Electricity Total',  {v: 51944, f: '51,944'}],
          ['Total Energy',  {v: 85833, f: '85,833'}],
        ]);

        var table = new google.visualization.Table(document.getElementById('table_div_2'));

        table.draw(data, {showRowNumber: false, width: '100%', height: '100%'});

      },
       
        toTop: function () {
         window.scrollTo({
         top: 0,
         behavior: 'smooth',
});
      }

    },
   
  mounted(){
       window.scrollTo(0, 0)
       this.drawChart();
       this.drawChart2();
       this.drawChart3();
       this.drawChart4();
       this.toTop();
  }
}
 

 
</script>



<style scoped>

  .divider {
    height: 1px;
    background: #444;
    margin: auto;
    max-width: 100%;
  }


p{
  color: #333333;
}

#header-wrap {
  height: 100vh;
  width: 100% ;
  background-image: url("../assets/CTDI-Environment/tree.jpg");
  background-size: cover;
  background-position: center;
}

#text{
    position: absolute;
    height: 600px;
    width: 70%;
    background-color:#F2F2F2;
    top: 490px;
    padding: 50px 80px;
    color: #333333;
    border-radius: 4px;
    right: 15%;
}

#text h3{
  color: #111111;
  font-size: 60px;
  padding-bottom: 15px;
}

#text p{
  font-size: 24px;
  line-height: 34px;
  max-width: 85%;
  margin: auto;
}

#barchart_material{
  margin: auto;
  width: 900px;
  height: 600px;
}

#mobile-chart-1{
  display: none;
}

.graph-text{
  padding-top: 100px;
  line-height: 30px;
  padding-bottom: 100px;
}

#chart_div{
  margin: auto;
  width: 900px;
  height: 600px;
}

#mobile-chart-2{
  display: none;
}


#white-space{
  padding-top: 525px;
}

#white-space-2{
  padding-top: 125px;
}

.title h4{
    color: #111111;
  font-size: 48px;
  padding-bottom: 100px;
  padding-top: 25px;
}

.graph-end{
  padding-bottom: 125px;
}

#header-wrap-2{
  height: 800px;
  width: 100% ;
  background-image: url("../assets/CTDI-Environment/water.jpg");
  background-size: cover;
  background-position: center;
}

#text-2{
   position: relative;
    height: 1400px;
    width: 70%;
   box-sizing: border-box;
    margin-left: auto;
    margin-right: auto;
    top: -170px;
    margin-bottom: -170px;
   background-color:#F2F2F2;
}

#text-2 h3{
  color: #111111;
  font-size: 60px;
  padding-bottom: 15px;
}

#text-2 p{
  color: #333333;
  font-size: 24px;
  line-height: 32px;
  max-width: 80%;
  margin: auto;
}

#header-wrap-3{
  height: 800px;
  width: 100% ;
  background-image: url("../assets/CTDI-Environment/box.jpg");
  background-size: cover;
  background-position: center;
}

#text-3{
   position: relative;
    height: 1000px;
    width: 70%;
   box-sizing: border-box;
    margin-left: auto;
    margin-right: auto;
    top: -170px;
    margin-bottom: -170px;
   background-color:#F2F2F2;
}

#text-3 h3{
  color: #111111;
  font-size: 60px;
  padding-bottom: 15px;
}

#text-3 p{
  color: #333333;
  font-size: 24px;
  line-height: 32px;
  max-width: 80%;
  margin: auto;
}
/* overlay -1 */
.content-1 {
   position: relative;
  width: 100%;
  max-width: 375px;
  margin: auto;
  overflow: hidden; 
}


.content-1 .content-overlay-1 {
  background: rgba(0,0,0,0.7);
  position: absolute;
  height: 63%;
  width: 100%;
  left: 0;
  top: 0;
  bottom: 0;
  right: 0;
  opacity: 0;
  -webkit-transition: all 0.4s ease-in-out 0s;
  -moz-transition: all 0.4s ease-in-out 0s;
  transition: all 0.4s ease-in-out 0s;
}

.content-1:hover .content-overlay-1{
  opacity: 1;
}


.content-image-1{
  width: 405px;
  height: 225px;
  border-radius: 5px;
}

.content-details-1 {
  position: absolute;
  text-align: center;
  padding-left: 1em;
  padding-right: 1em;
  width: 100%;
  top: 50%;
  left: 50%;
  opacity: 0;
  -webkit-transform: translate(-50%, -50%);
  -moz-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  -webkit-transition: all 0.3s ease-in-out 0s;
  -moz-transition: all 0.3s ease-in-out 0s;
  transition: all 0.3s ease-in-out 0s;
}

.content-1:hover .content-details-1{
  top: 35%;
  left: 50%;
  opacity: 1;
}

.content-details-1 h5{
  color: #fff;
  font-weight: 500;
  letter-spacing: 0.15em;
  margin-bottom: 0.5em;
  text-transform: uppercase;
  font-size: 28px;
}

.content-details-1 p{
  color: #fff !important;
  font-size: 17px  !important;
}

.fadeIn-top{
  top: 20%;
}

.content-1 h6{
  padding-bottom: 100px;
}

  h6{
      font-size: 19px;
  }

  a{
    color: #111111;
  }

  .text-p{
  color: #333333;
  font-size: 24px;
  line-height: 32px;
  max-width: 80%;
  margin: auto;
  }

  .pack-flex{
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    max-width: 100%;
    height: 700px;
    padding-top: 30px;
    justify-content: space-evenly;
  }

  .pack-item{
    max-width: 400px;
  }

  .title p{
  font-size: 24px;
  line-height: 34px;
  max-width: 85%;
  margin: auto;
  padding-bottom: 35px;
  }

  #table_div{
   margin: auto;
   width: 1200px;
   height: 400px;
  }

   #table_div_2{
   margin: auto;
   width: 1200px;
   height: 400px;
  }

  
/* hover overlay */
.content {
   position: relative;
  width: 100%;
  max-width: 375px;
  margin: auto;
  overflow: hidden; 
}


.content .content-overlay {
  background: rgba(0,0,0,0.7);
  position: absolute;
  height: 225px;
  width: 100%;
  left: 0;
  top: 0;
  bottom: 0;
  right: 0;
  opacity: 0;
  -webkit-transition: all 0.4s ease-in-out 0s;
  -moz-transition: all 0.4s ease-in-out 0s;
  transition: all 0.4s ease-in-out 0s;
}

.content:hover .content-overlay{
  opacity: 1;
}


.content-image{
  width: 405px;
  height: 225px;
  border-radius: 5px;
}

.content-details {
  position: absolute;
  text-align: center;
  padding-left: 1em;
  padding-right: 1em;
  width: 100%;
  top: 50%;
  left: 50%;
  opacity: 0;
  -webkit-transform: translate(-50%, -50%);
  -moz-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  -webkit-transition: all 0.3s ease-in-out 0s;
  -moz-transition: all 0.3s ease-in-out 0s;
  transition: all 0.3s ease-in-out 0s;
}

.content:hover .content-details{
  top: 50%;
  left: 50%;
  opacity: 1;
}

.content-details h3{
  color: #fff;
  font-weight: 500;
  letter-spacing: 0.15em;
  margin-bottom: 0.5em;
  text-transform: uppercase;
}

.content-details p{
  color: #fff;
  font-size: 0.9em;
}

.fadeIn-top{
  top: 20%;
}

.fadeIn-left{
  left: 20%;
}

.fadeIn-right{
  left: 80%;
}

.overlay-container{
  max-width: 85%;
  height: 600px;
  display: flex;
  flex-direction: row;
  margin: auto;
  justify-content: space-between;
  margin-bottom: 40px;
}





  #to-top a{
 text-align: right;
 color: #202124;
 font-size: 16px;
 line-height: 24px;
 font-weight: 500;
 margin-bottom: 40px;
 margin-top: 50px;
}

#to-top a{
  text-decoration: none;
}

#to-top a:hover{
  cursor: pointer;
}


@media (min-width: 1380px) { 
  
  #text{
    top: 800px;
    right: 15%;
 }

 #text h3{
  color: #111111;
  font-size: 62px;
}

#text-2{
    height: 1200px;
}

.pack-item{
    max-width: 500px;
  }
}


@media (max-width: 667px) {
    
    #text{
    height: 820px;
    width: 80%;
    top: 490px;
    right: 10%;
    padding: 30px 40px;
}

#text h3{
  color: #111111;
  font-size: 34px;
  padding-bottom: 15px;
}

#text p{
  font-size: 17px;
  max-width: 99%;
  line-height: 30px;
}

.title h4{
  font-size: 32px;
  padding-bottom: 100px;
  padding-top: 125px;
}
 
  #text-2{
    height: 2150px;
    width: 80%;
   box-sizing: border-box;
    margin-left: auto;
    margin-right: auto;
    top: -170px;
    margin-bottom: -170px;
   background-color:#F2F2F2;
}

#text-2 h3{
  color: #111111;
  font-size: 34px;
  padding-bottom: 15px;
}

#text-2 p{
  color: #333333;
  font-size: 17px;
  line-height: 30px;
  max-width: 80%;
  margin: auto;
}

#text-3{
    height: 1300px;
    width: 80%;
}

#text-3 h3{
  color: #111111;
  font-size: 34px;
  padding-bottom: 15px;
}

#text-3 p{
  font-size: 17px;
  line-height: 30px;
  max-width: 95%;
}

.pack-flex{
    display: flex;
    flex-direction: column;
    max-width: 97%;
    height: 1000px;
  }

/* hide chart on mobile ? 
#barchart_material
  margin: auto;
  width: 600px;
  height: 600px;
*/

#barchart_material{
  display: none;
}

#mobile-chart-1{
  display: inline-block;
}
#mobile-chart-1 img{
  height: 475px;
  width: 390px;
}

#chart_div{
  display: none;
}

#mobile-chart-2{
  display: inline-block;
}
#mobile-chart-2 img{
  height: 475px;
  width: 390px;
}

#table_div{
  height: 475px;
  width: 390px;
}

#table_div_2 {
  height: 475px;
  width: 390px;
}
  
#btn-group{
  display: none;
}

  .overlay-container{
  max-width: 85%;
  height: 650px;
  display: flex;
  flex-direction: column;
  margin: auto;
  justify-content: space-evenly;
  margin-top: 50px;
  margin-bottom: 50px;
}



}
</style>