<template>
<div> 
    <div id="header-wrap"></div>
    <div id="text"> <h3>Environment</h3> <p>CTDI has made a commitment to our employees, our community and our customers that we will continue to train and educate ourselves in waste minimization, hazardous material handling and regulatory compliance in an effort to support the longevity of the environment. CTDI is committed to protecting and preserving our natural resources in a productive and efficient manner through corporate initiatives such as recycling and resource management. CTDI has not incurred any regulatory fines or penalties as a result of improper environmental practices.</p> </div>
    <div id="white-space"></div>
        <div class="graph-title"><h4>Energy Use and Our Carbon Footprint</h4></div>
    <div id="barchart_material"></div>
    <div class="graph-text container"><p>Since a majority of CTDI's carbon emissions comes from our use of electricity; reducing electric usage is one of our primary goals. In 2016, we implemented several building related improvements that reduced our energy footprint across multiple facilities. One improvement was through the transition to cloud-based data storage, which allowed CTDI to decommission 3 data servers from its headquarters, saving over 17,000 kWh in energy costs for the servers themselves, as well as reducing the building's cooling needs.</p>
      <br>
       <p>In another main CTDI building in South Bend, IN, a lighting retrofit was conducted that replaced HID lights with LED. This will save an estimated 50% in energy usage along with a reduction of heat generated by our current fixtures, which will save close to 600 tons CO2e in one building alone. To continue to ensure energy improvements, CTDI has set a carbon target for itself, to reduce the intensity of our GHG emissions per square foot of building space by 2% over a five year period from our 2014 baseline, or a 10% reduction overall. As of 2016, CTDI has reached its target.</p>
      </div>
    <div id="chart_div"></div>
     <br>
     <br>
    <div id="btn-group">
      <button class="btn btn-outline-dark" id="none">No Format</button>
      <button class="btn btn-outline-dark" id="scientific">Scientific Notation</button>
      <button class="btn btn-outline-dark" id="decimal">Decimal</button>
      <button class="btn btn-outline-dark" id="short">Short</button>
    </div>
    <br><p class="container graph-end">Because the square footage increased more than originally predicted, CTDI is considering other performance standards.</p>
    <div id="header-wrap-2"></div>
    <div id="text-2"> <h3>Waste and Resource Conservation</h3> 
    <br><p>CTDI sends all waste from our seven Southeastern PA facilities to Blue River Resource in Wilmington, Delaware. The cutting edge Blue River facility ensures that any waste or recyclable material CTDI generates at the headquarter location, is responsibly processed and recycled. Blue River recycles 98% of all materials that comes in. The remaining 2% of materials are burned to generate electricity.</p>
    <br><p>CTDI is working to minimize printing in our daily operations, which leads to paper, ink and toner savings. We have enlisted an outside company to install network software to document our printing. We also recycle cooking by-products, such as oil in some of our locations.</p>
    <br><p>CTDI engages with our customers to reduce waste as well. CTDI has partnered with Verizon in a large electronics recycling initiative at CTDI's Headquarters in West Chester. CTDI and Verizon collected over 67,350 pounds of electronics from more than 500 CTDI and community participants, resulting in Verizon to achieve their "1 Million Pounds Recycled" milestone at the event. As a result of the event, 67,350 pounds of electronics were collected that equated to the avoidance of 105 metric tons (MT) of CO2. In addition, Verizon calculated that the FiOS STB Clean & Screen Program managed by CTDI, which allows Verizon to reuse STBs vs. new manufacturing, avoided 313K pounds of new material generation.  This collection of STBs equated to the avoidance of 454MT of CO2.</p>
    <br><p>CTDI is currently pursuing zero waste-to-landfill certifications at five of its facilities. Our Phoenix, AZ facility achieved this goal in June of 2017.</p>
    <br>
     <!-- overlay link -->
        <div class="content">
    <router-link to=/sustainability/ethics>
      <div class="content-overlay"></div>
      <img class="content-image" src="../assets/CTDI-Sustainability/ethics-1.jpg" alt="cabinet full of books"> 
      <div class="content-details fadeIn-top">
        <h5>Project Page</h5>
        <p>Click here for more information</p>
      </div>
    </router-link>
  </div>
    </div>
    <div id="white-space"></div>
</div>
</template>



<script>

  export default {
    name: 'Environment',
    data() {
      return {
       
    }
  },
    created() {
    
  },

   methods: {  
      drawChart: function() {
          var data = google.visualization.arrayToDataTable([
          ['tonnes CO²e', '2014', '2015', '2016'],
          ['Scope 1 (direct emissions)', 5946, 8798, 8157],
          ['Scope 2 (purchased electricity)', 34513, 32369, 36508]
        ]);

        var options = {
          chart: {
            title: 'Greenhouse Gas Emissions',
            subtitle: 'In 2016, CTDI utilized 85,833 MWh of energy and emitted 45,588 metric tons of CO²e.',
          },
          bars: 'vertical' 
        };

        var chart = new google.charts.Bar(document.getElementById('barchart_material'));

        chart.draw(data, google.charts.Bar.convertOptions(options));
      },
      drawChart2: function() {
               var data = google.visualization.arrayToDataTable([
          ['Year', 'Projected S1&2 emissions', 'Actual S1&2 emissions'],
          ['2014', 40485, 40485 ],
          ['2015', 41659, 41167 ],
          ['2016', 42867, 44665 ],
          ['2017', 44110, 0  ],
          ['2018', 45390, 0 ],
          ['2019', 46706, 0 ]
        ]);

        var options = {
          chart: {
            title: 'Direct Greenhouse Gas Emissions (in metric tons CO²e)',
            subtitle: 'projected intensity assumes 5% growth each year in square footage',
          },
          bars: 'horizontal', 
          hAxis: {format: 'decimal'},
          height: 600,
          width: 900,
          colors: ['#1b9e77', '#d95f02', '#7570b3']
        };

        var chart = new google.charts.Bar(document.getElementById('chart_div'));

        chart.draw(data, google.charts.Bar.convertOptions(options));

        var btns = document.getElementById('btn-group');

        btns.onclick = function (e) {

          if (e.target.tagName == 'BUTTON') {
            options.hAxis.format = e.target.id === 'none' ? '' : e.target.id;
            chart.draw(data, google.charts.Bar.convertOptions(options));
                 } 
        }
      },
    },
   
  mounted(){
       window.scrollTo(0, 0)
       this.drawChart();
       // this.drawChart2();
  }
}
 


</script>



<style scoped>

p{
  color: #333333;
}

#header-wrap {
  height: 100vh;
  width: 100% ;
  background-image: url("../assets/CTDI-Environment/tree.jpg");
  background-size: cover;
  background-position: center;
}

#text{
    position: absolute;
    height: 600px;
    width: 1050px;
    background-color:#F2F2F2;
    top: 490px;
    padding: 50px 80px;
    color: #333333;
    border-radius: 4px;
    right: 13%;
}

#text h3{
  color: #111111;
  font-size: 60px;
  padding-bottom: 15px;
}

#text p{
  font-size: 24px;
  line-height: 34px;
  max-width: 85%;
  margin: auto;
}

#barchart_material{
  margin: auto;
  width: 900px;
  height: 600px;
}

.graph-text{
  padding-top: 100px;
  line-height: 30px;
}

#chart_div{
  width: 900px;
  height: 600px;
}

#white-space{
  padding-top: 525px;
}

.graph-title h4{
    color: #111111;
  font-size: 48px;
  padding-bottom: 85px;
}

.graph-end{
  padding-bottom: 125px;
}

#header-wrap-2{
  height: 800px;
  width: 100% ;
  background-image: url("../assets/CTDI-Environment/water.jpg");
  background-size: cover;
  background-position: center;
}

#text-2{
   position: relative;
    height: 1300px;
    width: 1050px;
   box-sizing: border-box;
    margin-left: auto;
    margin-right: auto;
    top: -170px;
    margin-bottom: -170px;
   background-color:#F2F2F2;
    

}

#text-2 h3{
  color: #111111;
  font-size: 60px;
  padding-bottom: 15px;
}

#text-2 p{
  color: #333333;
  font-size: 24px;
  line-height: 32px;
  max-width: 80%;
  margin: auto;
}

/* overlay */
.content {
   position: relative;
  width: 100%;
  max-width: 375px;
  margin: auto;
  overflow: hidden; 
}


.content .content-overlay {
  background: rgba(0,0,0,0.7);
  position: absolute;
  height: 100%;
  width: 100%;
  left: 0;
  top: 0;
  bottom: 0;
  right: 0;
  opacity: 0;
  -webkit-transition: all 0.4s ease-in-out 0s;
  -moz-transition: all 0.4s ease-in-out 0s;
  transition: all 0.4s ease-in-out 0s;
}

.content:hover .content-overlay{
  opacity: 1;
}


.content-image{
  width: 405px;
  height: 225px;
}

.content-details {
  position: absolute;
  text-align: center;
  padding-left: 1em;
  padding-right: 1em;
  width: 100%;
  top: 50%;
  left: 50%;
  opacity: 0;
  -webkit-transform: translate(-50%, -50%);
  -moz-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  -webkit-transition: all 0.3s ease-in-out 0s;
  -moz-transition: all 0.3s ease-in-out 0s;
  transition: all 0.3s ease-in-out 0s;
}

.content:hover .content-details{
  top: 50%;
  left: 50%;
  opacity: 1;
}

.content-details h5{
  color: #fff;
  font-weight: 500;
  letter-spacing: 0.15em;
  margin-bottom: 0.5em;
  text-transform: uppercase;
  font-size: 28px;
}

.content-details p{
  color: #fff !important;
  font-size: 17px  !important;
}

.fadeIn-top{
  top: 20%;
}



@media (min-width: 1380px) { 
  
  #text{
    top: 800px;
    right: 430px;
 }

 #text h3{
  color: #111111;
  font-size: 62px;
}
}
</style>